AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/**/*
    - config/boot.rb
    - config/**/*
    - db/schema.rb
    - script/**/*
    - tmp/**/*
    - vendor/**/*
    - Rakefile
    - Gemfile
    - '**/helpers/dry_crud/**/*.rb'
    - '**/helpers/actions_helper*.rb'
    - '**/helpers/form_helper*.rb'
    - '**/helpers/format_helper*.rb'
    - '**/helpers/i18n_helper*.rb'
    - '**/helpers/table_helper*.rb'
    - '**/helpers/utility_helper*.rb'
    - app/controllers/dry_crud/*.rb
    - app/controllers/crud_controller.rb
    - spec/support/crud_*.rb
    - spec/controllers/crud_test_models_controller_spec.rb
  DisplayCopNames: true

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - db/migrate/*.rb
    - app/decorators/*_decorator.rb
    - app/controllers/reservations_controller.rb

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - lib/tasks/*.rake
    - spec/**/*_spec.rb

Metrics/LineLength:
  Enabled: true
  Exclude:
    - db/**/*
    - lib/tasks/dbdata.rake
    - spec/*_helper.rb

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/**/*
    - spec/*_helper.rb
    - app/controllers/reservations_controller.rb

Rails:
  Enabled: true

Rails/Date:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - app/helpers/datatable_helper.rb

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ModuleFunction:
  Enabled: false
