sudo: false
language: ruby
rvm:
  - 2.4.0
before_install: gem install bundler -v 1.14.6
script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
addons:
  postgresql: '9.5'
before_script:
  - psql -c 'create database cheidelacoriera_test;' -U postgres
