name: Lint and security (Ruby)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up RVM
      run: |
        curl -sSL https://get.rvm.io | bash
    - name: Set up .ruby-version
      run: |
        source $HOME/.rvm/scripts/rvm
        rvm install $(cat .ruby-version) --binary
        rvm --default use $(cat .ruby-version)
      # uses: actions/setup-ruby@v1
      # with:
      #   ruby-version: 2.7.x
    - name: Install PostgreSQL client
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Bundle install
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        source $HOME/.rvm/scripts/rvm
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Bundle audit
      run: |
        source $HOME/.rvm/scripts/rvm
        bundle exec bundle-audit --update
    - name: Brakeman security checks
      run: |
        source $HOME/.rvm/scripts/rvm
        bundle exec brakeman
    - name: Rubocop linting
      run: |
        source $HOME/.rvm/scripts/rvm
        bundle exec rubocop
    - name: Run tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        source $HOME/.rvm/scripts/rvm
        bundle exec rake db:test:prepare
        bundle exec rspec spec
